---
name: Packer
on:
  push:
  pull_request:

jobs:
  packer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packerfile:
          - app.json
          - db.json
          - immutable.json
          - ubuntu16.json


    steps:
      - uses: actions/checkout@v2
      - name: Validate
      - run: |
          packer validate -var-file=packer/variables.json.example packer/${{ matrix.packerfile }}
